name: spigotconsole
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  skeletons: ^0.0.3
  shared_preferences: ^2.1.0
  flutter_svg: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/top_header.svg

  fonts:
    - family: Minecraft
      fonts:
        - asset: assets/fonts/Minecraft.ttf
    - family: Minecrafter_3
      fonts:
        - asset: assets/fonts/Minecrafter_3.ttf
